services:
  bot:
    container_name: rebot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    networks:
      - rebot
    env_file:
      - .env
    volumes:
      - ./:/usr/app

  database:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - rebot
    volumes:
      - rebot-database:/var/lib/postgresql/data

networks:
  rebot:

volumes:
  rebot-database: